grpc:
  host: 0.0.0.0
  port: 50053
db:
  type: 'postgres'
  host: 'dpg-cgo4qh8u9tun42vc59k0-a.singapore-postgres.render.com'
  port: 5432
  database: 'nodekit'
  username: 'nodekit'
  password: 'ZSBFkcE1pwGULURoBYvL3UtpNFFt54ms'
  ssl: true
  synchronize: true
